### ISSUE TITLE
Update "psr/cache" dependency

### ISSUE THREAD

**Issue by SparkDragon** [softonic/guzzle-oauth2-middleware#18]
New Symfony version (6.0) requires psr/cache ^2.0| ^3.0 (from "symfony/cache" package). But softonic/guzzle-oauth2-middleware required psr/cache ^1.0.

It would be great to make it work with v2 and v3 in order to be able to use softonic/graphql-client in new Symfony projects.

**Comment by bu4ak** [comment]
Same issue

**Comment by joskfg** [comment]
Released 2.1.0 with psr/cache 2.0 and 3.0 support. Sorry for being late.
