### ISSUE TITLE
cache key prefix triggers InvalidArgumentException in psr-6 cache

### ISSUE THREAD

**Issue by bullett445** [softonic/guzzle-oauth2-middleware#21]
I get the following exception
Cache\Adapter\Common\Exception\InvalidArgumentException : Invalid key "oauth2-token-27aba17f1e43d187607aad81892bf3cc". Valid filenames must match [a-zA-Z0-9_\.! ].

psr-6 caches don't allow the minus in the cache key.

A pull request was created to fix that.

Jan

**Comment by joskfg** [comment]
PR Merged
